// <auto-generated />
using FutbolcuKartlariMVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbolcuKartlariMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FutbolcuKartlariMVC.Entities.Futbolcu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ayak")
                        .HasColumnType("int");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<byte>("Defans")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Degeri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Dribbling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Fizik")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Hiz")
                        .HasColumnType("tinyint");

                    b.Property<int>("Kilo")
                        .HasColumnType("int");

                    b.Property<int>("Mevki")
                        .HasColumnType("int");

                    b.Property<int>("MevkiID")
                        .HasColumnType("int");

                    b.Property<int>("OrtalamaDeger")
                        .HasColumnType("int");

                    b.Property<byte>("Pas")
                        .HasColumnType("tinyint");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Sut")
                        .HasColumnType("tinyint");

                    b.Property<int>("TakimID")
                        .HasColumnType("int");

                    b.Property<int>("UlkeID")
                        .HasColumnType("int");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TakimID");

                    b.HasIndex("UlkeID");

                    b.ToTable("futbolcular");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "Lucas",
                            Ayak = 1,
                            Boy = 166,
                            Defans = (byte)79,
                            Degeri = 15000000m,
                            Dribbling = (byte)80,
                            Fizik = (byte)78,
                            Hiz = (byte)76,
                            Kilo = 60,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 82,
                            Pas = (byte)77,
                            Soyad = "Torreira",
                            Sut = (byte)70,
                            TakimID = 1,
                            UlkeID = 1,
                            Yas = 27
                        },
                        new
                        {
                            ID = 2,
                            Ad = "Dries",
                            Ayak = 1,
                            Boy = 169,
                            Defans = (byte)40,
                            Degeri = 2600000m,
                            Dribbling = (byte)83,
                            Fizik = (byte)49,
                            Hiz = (byte)76,
                            Kilo = 61,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 81,
                            Pas = (byte)80,
                            Soyad = "Mertens",
                            Sut = (byte)80,
                            TakimID = 1,
                            UlkeID = 2,
                            Yas = 36
                        },
                        new
                        {
                            ID = 3,
                            Ad = "Wilfried",
                            Ayak = 1,
                            Boy = 180,
                            Defans = (byte)37,
                            Degeri = 20000000m,
                            Dribbling = (byte)85,
                            Fizik = (byte)76,
                            Hiz = (byte)90,
                            Kilo = 66,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 81,
                            Pas = (byte)72,
                            Soyad = "Zaha",
                            Sut = (byte)78,
                            TakimID = 1,
                            UlkeID = 3,
                            Yas = 31
                        },
                        new
                        {
                            ID = 4,
                            Ad = "Mauro",
                            Ayak = 1,
                            Boy = 181,
                            Defans = (byte)40,
                            Degeri = 20000000m,
                            Dribbling = (byte)73,
                            Fizik = (byte)72,
                            Hiz = (byte)67,
                            Kilo = 75,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 80,
                            Pas = (byte)69,
                            Soyad = "Icardi",
                            Sut = (byte)81,
                            TakimID = 1,
                            UlkeID = 4,
                            Yas = 30
                        },
                        new
                        {
                            ID = 5,
                            Ad = "Fernando",
                            Ayak = 1,
                            Boy = 190,
                            Defans = (byte)51,
                            Degeri = 1500000m,
                            Dribbling = (byte)77,
                            Fizik = (byte)83,
                            Hiz = (byte)76,
                            Kilo = 74,
                            Mevki = 1,
                            MevkiID = 0,
                            OrtalamaDeger = 80,
                            Pas = (byte)72,
                            Soyad = "Muslera",
                            Sut = (byte)80,
                            TakimID = 1,
                            UlkeID = 1,
                            Yas = 37
                        },
                        new
                        {
                            ID = 6,
                            Ad = "Hakim",
                            Ayak = 2,
                            Boy = 181,
                            Defans = (byte)50,
                            Degeri = 15000000m,
                            Dribbling = (byte)81,
                            Fizik = (byte)64,
                            Hiz = (byte)74,
                            Kilo = 65,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 80,
                            Pas = (byte)83,
                            Soyad = "Ziyech",
                            Sut = (byte)75,
                            TakimID = 1,
                            UlkeID = 5,
                            Yas = 30
                        },
                        new
                        {
                            ID = 7,
                            Ad = "Sacha",
                            Ayak = 1,
                            Boy = 178,
                            Defans = (byte)76,
                            Degeri = 17000000m,
                            Dribbling = (byte)75,
                            Fizik = (byte)84,
                            Hiz = (byte)86,
                            Kilo = 70,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 79,
                            Pas = (byte)65,
                            Soyad = "Boey",
                            Sut = (byte)55,
                            TakimID = 1,
                            UlkeID = 6,
                            Yas = 23
                        },
                        new
                        {
                            ID = 8,
                            Ad = "Kerem",
                            Ayak = 2,
                            Boy = 183,
                            Defans = (byte)71,
                            Degeri = 6000000m,
                            Dribbling = (byte)81,
                            Fizik = (byte)71,
                            Hiz = (byte)59,
                            Kilo = 75,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 79,
                            Pas = (byte)79,
                            Soyad = "Demirbay",
                            Sut = (byte)76,
                            TakimID = 1,
                            UlkeID = 7,
                            Yas = 30
                        },
                        new
                        {
                            ID = 9,
                            Ad = "Angelino",
                            Ayak = 2,
                            Boy = 171,
                            Defans = (byte)74,
                            Degeri = 11000000m,
                            Dribbling = (byte)82,
                            Fizik = (byte)68,
                            Hiz = (byte)71,
                            Kilo = 69,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 79,
                            Pas = (byte)81,
                            Soyad = "Tasende",
                            Sut = (byte)71,
                            TakimID = 1,
                            UlkeID = 8,
                            Yas = 26
                        },
                        new
                        {
                            ID = 10,
                            Ad = "Tanguy",
                            Ayak = 1,
                            Boy = 181,
                            Defans = (byte)68,
                            Degeri = 21000000m,
                            Dribbling = (byte)86,
                            Fizik = (byte)66,
                            Hiz = (byte)65,
                            Kilo = 76,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 78,
                            Pas = (byte)79,
                            Soyad = "Ndombele",
                            Sut = (byte)71,
                            TakimID = 1,
                            UlkeID = 6,
                            Yas = 26
                        },
                        new
                        {
                            ID = 11,
                            Ad = "Victor",
                            Ayak = 1,
                            Boy = 185,
                            Defans = (byte)79,
                            Degeri = 19000000m,
                            Dribbling = (byte)66,
                            Fizik = (byte)84,
                            Hiz = (byte)64,
                            Kilo = 78,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 78,
                            Pas = (byte)59,
                            Soyad = "Nelsson",
                            Sut = (byte)43,
                            TakimID = 1,
                            UlkeID = 9,
                            Yas = 25
                        },
                        new
                        {
                            ID = 12,
                            Ad = "Sergio",
                            Ayak = 1,
                            Boy = 181,
                            Defans = (byte)67,
                            Degeri = 6000000m,
                            Dribbling = (byte)74,
                            Fizik = (byte)62,
                            Hiz = (byte)51,
                            Kilo = 78,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 78,
                            Pas = (byte)82,
                            Soyad = "Oliveira",
                            Sut = (byte)76,
                            TakimID = 1,
                            UlkeID = 10,
                            Yas = 31
                        },
                        new
                        {
                            ID = 13,
                            Ad = "Kerem",
                            Ayak = 1,
                            Boy = 173,
                            Defans = (byte)38,
                            Degeri = 17000000m,
                            Dribbling = (byte)79,
                            Fizik = (byte)56,
                            Hiz = (byte)84,
                            Kilo = 71,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 77,
                            Pas = (byte)71,
                            Soyad = "Aktürkoğlu",
                            Sut = (byte)73,
                            TakimID = 1,
                            UlkeID = 11,
                            Yas = 25
                        },
                        new
                        {
                            ID = 14,
                            Ad = "Abdulkerim",
                            Ayak = 2,
                            Boy = 190,
                            Defans = (byte)78,
                            Degeri = 7500000m,
                            Dribbling = (byte)65,
                            Fizik = (byte)83,
                            Hiz = (byte)61,
                            Kilo = 80,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 77,
                            Pas = (byte)64,
                            Soyad = "Bardakçı",
                            Sut = (byte)32,
                            TakimID = 1,
                            UlkeID = 11,
                            Yas = 29
                        },
                        new
                        {
                            ID = 15,
                            Ad = "Davinson",
                            Ayak = 1,
                            Boy = 187,
                            Defans = (byte)77,
                            Degeri = 14000000m,
                            Dribbling = (byte)64,
                            Fizik = (byte)78,
                            Hiz = (byte)73,
                            Kilo = 81,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 77,
                            Pas = (byte)54,
                            Soyad = "Sanchez",
                            Sut = (byte)47,
                            TakimID = 1,
                            UlkeID = 12,
                            Yas = 27
                        },
                        new
                        {
                            ID = 16,
                            Ad = "Cedric",
                            Ayak = 1,
                            Boy = 182,
                            Defans = (byte)36,
                            Degeri = 3400000m,
                            Dribbling = (byte)73,
                            Fizik = (byte)63,
                            Hiz = (byte)81,
                            Kilo = 73,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 76,
                            Pas = (byte)66,
                            Soyad = "Bakambu",
                            Sut = (byte)77,
                            TakimID = 1,
                            UlkeID = 13,
                            Yas = 32
                        },
                        new
                        {
                            ID = 17,
                            Ad = "Mateus",
                            Ayak = 2,
                            Boy = 175,
                            Defans = (byte)41,
                            Degeri = 24000000m,
                            Dribbling = (byte)79,
                            Fizik = (byte)55,
                            Hiz = (byte)81,
                            Kilo = 70,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 76,
                            Pas = (byte)72,
                            Soyad = "Tete",
                            Sut = (byte)72,
                            TakimID = 1,
                            UlkeID = 14,
                            Yas = 23
                        },
                        new
                        {
                            ID = 18,
                            Ad = "Günay",
                            Ayak = 1,
                            Boy = 187,
                            Defans = (byte)55,
                            Degeri = 1500000m,
                            Dribbling = (byte)76,
                            Fizik = (byte)71,
                            Hiz = (byte)73,
                            Kilo = 85,
                            Mevki = 1,
                            MevkiID = 0,
                            OrtalamaDeger = 74,
                            Pas = (byte)72,
                            Soyad = "Güvenç",
                            Sut = (byte)72,
                            TakimID = 1,
                            UlkeID = 11,
                            Yas = 32
                        },
                        new
                        {
                            ID = 19,
                            Ad = "Kaan",
                            Ayak = 1,
                            Boy = 184,
                            Defans = (byte)72,
                            Degeri = 3700000m,
                            Dribbling = (byte)67,
                            Fizik = (byte)74,
                            Hiz = (byte)58,
                            Kilo = 84,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 72,
                            Pas = (byte)69,
                            Soyad = "Ayhan",
                            Sut = (byte)53,
                            TakimID = 1,
                            UlkeID = 11,
                            Yas = 29
                        },
                        new
                        {
                            ID = 20,
                            Ad = "Barış Alper",
                            Ayak = 1,
                            Boy = 186,
                            Defans = (byte)37,
                            Degeri = 5500000m,
                            Dribbling = (byte)71,
                            Fizik = (byte)84,
                            Hiz = (byte)87,
                            Kilo = 72,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 72,
                            Pas = (byte)64,
                            Soyad = "Yılmaz",
                            Sut = (byte)70,
                            TakimID = 1,
                            UlkeID = 11,
                            Yas = 23
                        },
                        new
                        {
                            ID = 21,
                            Ad = "Mert",
                            Ayak = 1,
                            Boy = 196,
                            Defans = (byte)17,
                            Degeri = 1500000m,
                            Dribbling = (byte)73,
                            Fizik = (byte)53,
                            Hiz = (byte)56,
                            Kilo = 92,
                            Mevki = 1,
                            MevkiID = 0,
                            OrtalamaDeger = 75,
                            Pas = (byte)35,
                            Soyad = "Günok",
                            Sut = (byte)22,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 34
                        },
                        new
                        {
                            ID = 22,
                            Ad = "Daniel",
                            Ayak = 1,
                            Boy = 186,
                            Defans = (byte)84,
                            Degeri = 12000000m,
                            Dribbling = (byte)77,
                            Fizik = (byte)82,
                            Hiz = (byte)78,
                            Kilo = 79,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 83,
                            Pas = (byte)71,
                            Soyad = "Amartey",
                            Sut = (byte)64,
                            TakimID = 2,
                            UlkeID = 15,
                            Yas = 28
                        },
                        new
                        {
                            ID = 23,
                            Ad = "Eric",
                            Ayak = 1,
                            Boy = 187,
                            Defans = (byte)85,
                            Degeri = 4000000m,
                            Dribbling = (byte)73,
                            Fizik = (byte)85,
                            Hiz = (byte)81,
                            Kilo = 77,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 85,
                            Pas = (byte)70,
                            Soyad = "Bailly",
                            Sut = (byte)51,
                            TakimID = 2,
                            UlkeID = 3,
                            Yas = 29
                        },
                        new
                        {
                            ID = 24,
                            Ad = "Rachid",
                            Ayak = 2,
                            Boy = 182,
                            Defans = (byte)28,
                            Degeri = 4000000m,
                            Dribbling = (byte)81,
                            Fizik = (byte)58,
                            Hiz = (byte)71,
                            Kilo = 70,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 78,
                            Pas = (byte)81,
                            Soyad = "Ghezzal",
                            Sut = (byte)72,
                            TakimID = 2,
                            UlkeID = 16,
                            Yas = 31
                        },
                        new
                        {
                            ID = 25,
                            Ad = "Necip",
                            Ayak = 1,
                            Boy = 180,
                            Defans = (byte)68,
                            Degeri = 600000m,
                            Dribbling = (byte)63,
                            Fizik = (byte)72,
                            Hiz = (byte)54,
                            Kilo = 72,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 68,
                            Pas = (byte)61,
                            Soyad = "Uysal",
                            Sut = (byte)56,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 32
                        },
                        new
                        {
                            ID = 26,
                            Ad = "Gedson",
                            Ayak = 1,
                            Boy = 183,
                            Defans = (byte)75,
                            Degeri = 17000000m,
                            Dribbling = (byte)80,
                            Fizik = (byte)77,
                            Hiz = (byte)79,
                            Kilo = 63,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 78,
                            Pas = (byte)76,
                            Soyad = "Fernandes",
                            Sut = (byte)73,
                            TakimID = 2,
                            UlkeID = 10,
                            Yas = 24
                        },
                        new
                        {
                            ID = 27,
                            Ad = "Alex Oxlade",
                            Ayak = 1,
                            Boy = 175,
                            Defans = (byte)67,
                            Degeri = 6000000m,
                            Dribbling = (byte)81,
                            Fizik = (byte)72,
                            Hiz = (byte)78,
                            Kilo = 70,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 77,
                            Pas = (byte)76,
                            Soyad = "Chamberlain",
                            Sut = (byte)74,
                            TakimID = 2,
                            UlkeID = 17,
                            Yas = 30
                        },
                        new
                        {
                            ID = 28,
                            Ad = "Ante",
                            Ayak = 1,
                            Boy = 185,
                            Defans = (byte)46,
                            Degeri = 5000000m,
                            Dribbling = (byte)77,
                            Fizik = (byte)77,
                            Hiz = (byte)80,
                            Kilo = 80,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 77,
                            Pas = (byte)72,
                            Soyad = "Rebic",
                            Sut = (byte)77,
                            TakimID = 2,
                            UlkeID = 18,
                            Yas = 30
                        },
                        new
                        {
                            ID = 29,
                            Ad = "Milot",
                            Ayak = 1,
                            Boy = 277,
                            Defans = (byte)50,
                            Degeri = 8500000m,
                            Dribbling = (byte)77,
                            Fizik = (byte)73,
                            Hiz = (byte)81,
                            Kilo = 73,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 76,
                            Pas = (byte)71,
                            Soyad = "Rashica",
                            Sut = (byte)75,
                            TakimID = 2,
                            UlkeID = 19,
                            Yas = 27
                        },
                        new
                        {
                            ID = 30,
                            Ad = "Arthur",
                            Ayak = 2,
                            Boy = 179,
                            Defans = (byte)70,
                            Degeri = 6000000m,
                            Dribbling = (byte)79,
                            Fizik = (byte)79,
                            Hiz = (byte)79,
                            Kilo = 80,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 76,
                            Pas = (byte)73,
                            Soyad = "Masuaku",
                            Sut = (byte)61,
                            TakimID = 2,
                            UlkeID = 13,
                            Yas = 30
                        },
                        new
                        {
                            ID = 31,
                            Ad = "Valentin",
                            Ayak = 1,
                            Boy = 175,
                            Defans = (byte)72,
                            Degeri = 6000000m,
                            Dribbling = (byte)75,
                            Fizik = (byte)76,
                            Hiz = (byte)84,
                            Kilo = 75,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 76,
                            Pas = (byte)65,
                            Soyad = "Roiser",
                            Sut = (byte)52,
                            TakimID = 2,
                            UlkeID = 6,
                            Yas = 27
                        },
                        new
                        {
                            ID = 32,
                            Ad = "Amir",
                            Ayak = 1,
                            Boy = 179,
                            Defans = (byte)71,
                            Degeri = 8000000m,
                            Dribbling = (byte)72,
                            Fizik = (byte)77,
                            Hiz = (byte)71,
                            Kilo = 70,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 75,
                            Pas = (byte)71,
                            Soyad = "Hadziahmetovic",
                            Sut = (byte)60,
                            TakimID = 2,
                            UlkeID = 20,
                            Yas = 26
                        },
                        new
                        {
                            ID = 33,
                            Ad = "Cenk",
                            Ayak = 1,
                            Boy = 183,
                            Defans = (byte)36,
                            Degeri = 3000000m,
                            Dribbling = (byte)72,
                            Fizik = (byte)72,
                            Hiz = (byte)66,
                            Kilo = 78,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 75,
                            Pas = (byte)67,
                            Soyad = "Tosun",
                            Sut = (byte)77,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 32
                        },
                        new
                        {
                            ID = 34,
                            Ad = "Omar",
                            Ayak = 2,
                            Boy = 191,
                            Defans = (byte)73,
                            Degeri = 3800000m,
                            Dribbling = (byte)55,
                            Fizik = (byte)84,
                            Hiz = (byte)64,
                            Kilo = 90,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 74,
                            Pas = (byte)48,
                            Soyad = "Collay",
                            Sut = (byte)31,
                            TakimID = 2,
                            UlkeID = 21,
                            Yas = 31
                        },
                        new
                        {
                            ID = 35,
                            Ad = "Jean",
                            Ayak = 1,
                            Boy = 189,
                            Defans = (byte)71,
                            Degeri = 4800000m,
                            Dribbling = (byte)71,
                            Fizik = (byte)82,
                            Hiz = (byte)54,
                            Kilo = 85,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 74,
                            Pas = (byte)70,
                            Soyad = "Onana",
                            Sut = (byte)66,
                            TakimID = 2,
                            UlkeID = 22,
                            Yas = 23
                        },
                        new
                        {
                            ID = 36,
                            Ad = "Salih",
                            Ayak = 1,
                            Boy = 182,
                            Defans = (byte)66,
                            Degeri = 5000000m,
                            Dribbling = (byte)75,
                            Fizik = (byte)65,
                            Hiz = (byte)57,
                            Kilo = 80,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 74,
                            Pas = (byte)75,
                            Soyad = "Ucan",
                            Sut = (byte)70,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 29
                        },
                        new
                        {
                            ID = 37,
                            Ad = "Ersin",
                            Ayak = 1,
                            Boy = 195,
                            Defans = (byte)11,
                            Degeri = 3500000m,
                            Dribbling = (byte)32,
                            Fizik = (byte)40,
                            Hiz = (byte)38,
                            Kilo = 88,
                            Mevki = 1,
                            MevkiID = 0,
                            OrtalamaDeger = 74,
                            Pas = (byte)20,
                            Soyad = "Destanoglu",
                            Sut = (byte)16,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 22
                        },
                        new
                        {
                            ID = 38,
                            Ad = "Onur",
                            Ayak = 1,
                            Boy = 179,
                            Defans = (byte)64,
                            Degeri = 3800000m,
                            Dribbling = (byte)70,
                            Fizik = (byte)72,
                            Hiz = (byte)77,
                            Kilo = 80,
                            Mevki = 3,
                            MevkiID = 0,
                            OrtalamaDeger = 70,
                            Pas = (byte)69,
                            Soyad = "Bulut",
                            Sut = (byte)59,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 29
                        },
                        new
                        {
                            ID = 39,
                            Ad = "Jackson",
                            Ayak = 1,
                            Boy = 180,
                            Defans = (byte)35,
                            Degeri = 4500000m,
                            Dribbling = (byte)71,
                            Fizik = (byte)71,
                            Hiz = (byte)81,
                            Kilo = 80,
                            Mevki = 4,
                            MevkiID = 0,
                            OrtalamaDeger = 70,
                            Pas = (byte)58,
                            Soyad = "Muleko",
                            Sut = (byte)71,
                            TakimID = 2,
                            UlkeID = 13,
                            Yas = 24
                        },
                        new
                        {
                            ID = 40,
                            Ad = "Umut",
                            Ayak = 2,
                            Boy = 178,
                            Defans = (byte)62,
                            Degeri = 4500000m,
                            Dribbling = (byte)65,
                            Fizik = (byte)70,
                            Hiz = (byte)74,
                            Kilo = 73,
                            Mevki = 2,
                            MevkiID = 0,
                            OrtalamaDeger = 67,
                            Pas = (byte)59,
                            Soyad = "Meras",
                            Sut = (byte)42,
                            TakimID = 2,
                            UlkeID = 11,
                            Yas = 27
                        });
                });

            modelBuilder.Entity("FutbolcuKartlariMVC.Entities.Takim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("TakimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("takimlar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            TakimAdi = "Galatasaray"
                        },
                        new
                        {
                            ID = 2,
                            TakimAdi = "Besiktas"
                        });
                });

            modelBuilder.Entity("FutbolcuKartlariMVC.Entities.Ulke", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("UlkeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ulkeler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            UlkeAdi = "Uruguay"
                        },
                        new
                        {
                            ID = 2,
                            UlkeAdi = "Belçika"
                        },
                        new
                        {
                            ID = 3,
                            UlkeAdi = "Fildişi Sahili"
                        },
                        new
                        {
                            ID = 4,
                            UlkeAdi = "Arjantin"
                        },
                        new
                        {
                            ID = 5,
                            UlkeAdi = "Fas"
                        },
                        new
                        {
                            ID = 6,
                            UlkeAdi = "Fransa"
                        },
                        new
                        {
                            ID = 7,
                            UlkeAdi = "Almanya"
                        },
                        new
                        {
                            ID = 8,
                            UlkeAdi = "İspanya"
                        },
                        new
                        {
                            ID = 9,
                            UlkeAdi = "Danimarka"
                        },
                        new
                        {
                            ID = 10,
                            UlkeAdi = "Portekiz"
                        },
                        new
                        {
                            ID = 11,
                            UlkeAdi = "Türkiye"
                        },
                        new
                        {
                            ID = 12,
                            UlkeAdi = "Kolombiya"
                        },
                        new
                        {
                            ID = 13,
                            UlkeAdi = "Congo"
                        },
                        new
                        {
                            ID = 14,
                            UlkeAdi = "Brezilya"
                        },
                        new
                        {
                            ID = 15,
                            UlkeAdi = "Gana"
                        },
                        new
                        {
                            ID = 16,
                            UlkeAdi = "Cezayir"
                        },
                        new
                        {
                            ID = 17,
                            UlkeAdi = "İngiltere"
                        },
                        new
                        {
                            ID = 18,
                            UlkeAdi = "Hırvatistan"
                        },
                        new
                        {
                            ID = 19,
                            UlkeAdi = "Kosova"
                        },
                        new
                        {
                            ID = 20,
                            UlkeAdi = "Bosna Hersek"
                        },
                        new
                        {
                            ID = 21,
                            UlkeAdi = "Gambiya"
                        },
                        new
                        {
                            ID = 22,
                            UlkeAdi = "Kamerun"
                        });
                });

            modelBuilder.Entity("FutbolcuKartlariMVC.Entities.Futbolcu", b =>
                {
                    b.HasOne("FutbolcuKartlariMVC.Entities.Takim", "Takim")
                        .WithMany("Futbolcular")
                        .HasForeignKey("TakimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbolcuKartlariMVC.Entities.Ulke", "Ulke")
                        .WithMany("Futbolcular")
                        .HasForeignKey("UlkeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Takim");

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("FutbolcuKartlariMVC.Entities.Takim", b =>
                {
                    b.Navigation("Futbolcular");
                });

            modelBuilder.Entity("FutbolcuKartlariMVC.Entities.Ulke", b =>
                {
                    b.Navigation("Futbolcular");
                });
#pragma warning restore 612, 618
        }
    }
}
